### ISSUE TITLE
Unable to quit RStudio "when browser is active"

### ISSUE THREAD

**Issue by dontgoratingmyheart** [matgbar/IBI_VizEdit#31]
Trying just to close out of R, but keep getting this error message when prompted to save after X'ing out:
![0301181108](https://user-images.githubusercontent.com/36671027/36855344-2af645f6-1d41-11e8-97a4-5c3473c3a7f8.jpg)

**Comment by matgbar** [comment]
I went through and checked the code that is currently up on the repository. There does not appear to be any lines of code with an active `browser()` feature (all have been commented out using `#`). This must be an old version of the program that was uploaded to the repository before I had finished debugging some sections. 

To continue using the program even when these debugging functions have been added to the program you can simply hit the continue button displayed at the top of the console. Still let me know because the versions I put on the repository should have all of the `browser()` commands turned off.

**Comment by dontgoratingmyheart** [comment]
It was using the latest version uploaded Thursday.  Just went back in and
found 2 browser() commands w/o the # in front, program appears to be
working now.

--

Benjamin Weinberg
B.A. Psychology and B.A. Criminology and Criminal Justice Candidate
University of Maryland, Class of 2018

**Comment by matgbar** [comment]
What were the lines of code where the browser() function was still active?
