### ISSUE TITLE
Restore IBI Crash 

### ISSUE THREAD

**Issue by TrevorAngert** [matgbar/IBI_VizEdit#40]
**File:** 010_T3
**Issue:** In a very messy section of the file, I added a point which drastically changed the data. I attempted to use the restore IBI function to get rid of it, and the program crashed.
**Warning Message**
```
Warning: Error in data.frame: arguments imply differing number of rows: 1, 0
Stack trace (innermost first):
    66: data.frame
    65: observeEventHandler [C:/Users/tangert/Documents/IBI VizEdit/IBI_VizEdit-master/VizEdit_v1_2_0.R#1383]
     1: runApp
ERROR: [on_request_read] connection reset by peer
```

**Comment by matgbar** [comment]
I have a guess at what happened. It is possible that following the edit, the selection window you created within which to restore the old IBI values actually did not cover any of the locations of the old IBI values. It is not a "true" undo button. It enables you to select an area of the plot and restore all original IBI values within that area. 

Still this is useful to know. I'll change it so that a warning comes up instead of a crash.
